services:

  postgres_container:
    image: postgres:15-alpine
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
        - POSTGRES_DB=socialized
        - POSTGRES_USER=mykyta
        - POSTGRES_PASSWORD=Pass1234!
    restart: always
    volumes:
      - socialized_db_data:/var/lib/postgresql/data
    
  backend_socalized:
    container_name: backend_socalized
    build:
      context: ./src/Socialized.Backend/WebApiCompose/WebApiCompose
      dockerfile: Dockerfile
    image: ${DOCKER_REGISTRY-}webapicompose
    ports:
        - "8000:80"
    restart: on-failure
    environment:
      - ConnectionStrings__DefaultConnection=host=postgres_container;port=5432;database=socialized;username=mykyta;password=Pass1234!;Pooling=true;
  
volumes:
  socialized_db_data: